const SHEET_ID = "1ZG49Svf_a7sjtxv87Zx_tnk8_ymVurhcCm0YzrgKByo";
const SHEET_NAME = "reports";

fetch(`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${SHEET_NAME}&t=${Date.now()}`)
  .then(res => res.text())
  .then(text => {
    const json = JSON.parse(
      text.substring(text.indexOf('{'), text.lastIndexOf('}') + 1)
    );

    let html = "";

    json.table.rows.forEach(r => {
      if(!r.c) return;

      const date = r.c[0]?.v;
      const period = r.c[1]?.v;
      const orders = r.c[2]?.v;
      const sales = r.c[3]?.v;
      const paid = r.c[4]?.v;
      const balance = r.c[5]?.v;
      const by = r.c[6]?.v;

      html += `
        <div class="report">
          <b>${period.toUpperCase()} REPORT</b>
          <span class="badge">${period}</span><br><br>

          Date: ${date}<br>
          Total Orders: ${orders}<br>
          Total Sales: ₹${sales}<br>
          Paid Amount: ₹${paid}<br>
          Balance: ₹${balance}<br>
          <span class="small">Generated by: ${by}</span>
        </div>
      `;
    });

    document.getElementById("reportList").innerHTML =
      html || "No reports found";

  })
  .catch(() => {
    document.getElementById("reportList").innerText =
      "Error loading reports";
  });
