const SHEET_ID = "1ZG49Svf_a7sjtxv87Zx_tnk8_ymVurhcCm0YzrgKByo";
const SHEET_NAME = "reports";

const company = (localStorage.getItem("company") || "").toLowerCase();

function formatDate(v){
  if(!v) return "";
  if(typeof v === "string") return v;
  if(v.getFullYear){
    const y = v.getFullYear();
    const m = String(v.getMonth()+1).padStart(2,"0");
    const d = String(v.getDate()).padStart(2,"0");
    return `${y}-${m}-${d}`;
  }
  return "";
}

fetch(`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${SHEET_NAME}&t=${Date.now()}`)
.then(res => res.text())
.then(text => {
  const json = JSON.parse(
    text.substring(text.indexOf("{"), text.lastIndexOf("}") + 1)
  );

  let html = "";

  json.table.rows.forEach(r => {
    if(!r.c) return;

    const rowCompany = (r.c[2]?.v || "").toLowerCase();
    if(rowCompany !== company) return; // 🔒 company isolation

    const date   = formatDate(r.c[0]?.v);
    const period = r.c[1]?.v || "";
    const orders = r.c[3]?.v || 0;
    const sales  = r.c[4]?.v || 0;
    const paid   = r.c[5]?.v || 0;
    const bal    = r.c[6]?.v || 0;
    const by     = r.c[7]?.v || "";

    html += `
      <div class="report">
        <b>${period} Report</b><br>
        <span class="small">${date}</span><br><br>

        Orders: ${orders}<br>
        Sales: ₹${sales}<br>
        Paid: ₹${paid}<br>
        Balance: ₹${bal}<br>

        <span class="small">Generated by: ${by}</span>
      </div>
    `;
  });

  document.getElementById("reportList").innerHTML =
    html || "No reports available";

})
.catch(err => {
  console.error("REPORT LOAD ERROR:", err);
  document.getElementById("reportList").innerText =
    "Error loading reports";
});
